# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0012_auto_20180730_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
