# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0014_auto_20180823_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
