# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0016_auto_20180902_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
