# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0019_auto_20180903_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
