# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0020_auto_20180903_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.FloatField(choices=[(1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
