# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-06 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0027_auto_20180905_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
