# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-09 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0030_auto_20180909_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(),
        ),
    ]
