# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0031_auto_20180909_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
