# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0032_auto_20180910_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
