# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-12 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0037_auto_20180911_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
